# Generated by Django 4.1.6 on 2023-02-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_remove_article_category_alter_article_edit_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='categories',
        ),
    ]
